{
 "title": "All_added_manually",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "process_resident_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job='prometheus',instance='hifolks_flask_app:5000'}",
     "legendFormat": "process_resident_memory_bytes"
    }
   ]
  },
  {
   "title": "process_cpu_seconds_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{job='prometheus',instance='hifolks_flask_app:5000'}[5m])",
     "legendFormat": "process_cpu_seconds_total"
    }
   ]
  },
  {
   "title": "python_gc_objects_collected_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "python_gc_objects_collected_total{generation=\"2\",instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "python_gc_objects_collected_total generation=\"2\""
    },
    {
     "expr": "python_gc_objects_collected_total{generation=\"1\",instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "python_gc_objects_collected_total generation=\"1\""
    },
    {
     "expr": "python_gc_objects_collected_total{generation=\"0\",instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "python_gc_objects_collected_total generation=\"0\""
    }
   ]
  },
  {
   "title": "python_gc_collections_total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "python_gc_collections_total{generation=\"0\",instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "python_gc_collections_total generation=\"0\""
    },
    {
     "expr": "python_gc_collections_total{generation=\"1\",instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "python_gc_collections_total generation=\"1\""
    },
    {
     "expr": "python_gc_collections_total{generation=\"2\",instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "python_gc_collections_total generation=\"2\""
    }
   ]
  },
  {
   "title": "process_virtual_memory_bytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "process_virtual_memory_bytes"
    }
   ]
  },
  {
   "title": "process_open_fds_and_max_fds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_max_fds{instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "process_max_fds"
    },
    {
     "expr": "process_open_fds{instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "process_open_fds"
    }
   ]
  },
  {
   "title": "process_start_time_seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_start_time_seconds{instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "process_start_time_seconds"
    }
   ]
  },
  {
   "title": "my_inprogress_requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "my_inprogress_requests{instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "my_inprogress_requests"
    }
   ]
  },
  {
   "title": "my_failures_created_and_total",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "my_failures_created{instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "my_failures_created"
    },
    {
     "expr": "my_failures_total{instance=\"hifolks_flask_app:5000\",job=\"prometheus\"}",
     "legendFormat": "my_failures_total"
    }
   ]
  }
 ]
}